name: "Bulidability and Sanity"
on:
  push:
    branches:
      - master
      - '*'
      - '!libretro'

jobs:
  sanity:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, ubuntu-20.04]
        cc: [gcc, clang]
        include:
        - os: macos-latest
          cc: clang
          extra_targets: cocoa ios-ipa ios-deb
        exclude:
        - os: macos-latest
          cc: gcc
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        shell: bash
        run: |
          ./.github/actions/install_deps.sh ${{ matrix.os }}
      - name: Build
        run: |
          ${{ matrix.cc }} -v; (make -j all CONF=release CC=${{ matrix.cc }} || (echo "==== Build Failed ==="; make all CONF=release CC=${{ matrix.cc }}))
      - name: Sanity tests
        shell: bash
        run: |
          ./.github/actions/sanity_tests.sh
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: sameboy-canary-${{ matrix.os }}-${{ matrix.cc }}
          path: |
            build/bin
            build/lib
            build/include
